name: CI

on: [pull_request, pull_request_review]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo $GITHUB_SHA
        echo ${{ github.event.pull_request.head.sha }}
        echo ${{ github.event.pull_request.head }}
      
  test: 
     
    runs-on: ubuntu-latest
    steps: 
        - name: CI2
          uses: ypicard/get-branch-name-github-action@v1
          id: get-mybranch
        - name: print-branch 
          run: echo "${{ steps.get-mybranch.outputs.branch }}" - "${{ steps.gt-mybranch.outputs.tag }}"
          
  new-item:
    runs-on: ubuntu-latest
    steps: 
      - uses: jackjamieson2/GitHub-issues-to-pdf@v1
      - name: other-stuff
        run: python GitHub-issues-to-pdf.py
                 
