name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo I wnat to add yet another line to this file
        def process_pull_request(pull_request)
        @client.create_status(pull_request['base']['repo']['full_name'], pull_request['head']['sha'], 'pending')
        sleep 2 # do busy work...
        @client.create_status(pull_request['base']['repo']['full_name'], pull_request['head']['sha'], 'success')
        puts "Pull request processed!"
        end
